import type { HospitalShiftRecord } from '@/types/hospital';

export const mockHospitalShifts: HospitalShiftRecord[] = [
  {
    id: 'mock-1',
    reference: 'SH-EM-1027',
    date: '27',
    month: 'OCT',
    year: '26',
    title: 'Emergency Medicine – Night Shift',
    location: 'Sydney, NSW',
    time: '08:00 PM – 08:00 AM',
    status: 'published',
    price: 180,
  },
  {
    id: 'mock-2',
    reference: 'SH-GP-1025',
    date: '25',
    month: 'OCT',
    year: '26',
    title: 'General Practice – Day Shift',
    location: 'Melbourne, VIC',
    time: '08:00 AM – 04:00 PM',
    status: 'filled',
    price: 140,
  },
  {
    id: 'mock-3',
    reference: 'SH-GP-1021',
    date: '21',
    month: 'OCT',
    year: '26',
    title: 'General Practice – Day Shift',
    location: 'Melbourne, VIC',
    time: '08:00 AM – 04:00 PM',
    status: 'filled',
    price: 140,
  },
  {
    id: 'mock-4',
    reference: 'SH-AN-1017',
    date: '17',
    month: 'OCT',
    year: '26',
    title: 'Anaesthetics – Evening Shift',
    location: 'Sydney, NSW',
    time: '04:00 PM – 12:00 AM',
    status: 'draft',
    price: 180,
  },
];
