import { DoctorApplication } from '@/types/myApplications';

export const mockApplications: DoctorApplication[] = [
  {
    id: 1,
    title: 'General Practitioner – Morning Shift',
    hospitalName: "St. Mary's Hospital Sydney, NSW",
    date: '27',
    month: 'OCT',
    year: '26',
    time: '08:00 AM – 02:00 PM',
    status: 'pending',
  },
  {
    id: 2,
    title: 'Emergency Department – Night Shift',
    hospitalName: 'Royal Care Hospital',
    date: '27',
    month: 'OCT',
    year: '26',
    time: '08:00 PM – 06:00 AM',
    status: 'accepted',
  },
  {
    id: 3,
    title: 'Locum GP – Day Shift',
    hospitalName: 'Sunrise Medical Centre',
    date: '27',
    month: 'OCT',
    year: '26',
    time: '08:00 AM – 02:00 PM',
    status: 'rejected',
  },
  {
    id: 4,
    title: 'GP – Weekend Shift',
    hospitalName: 'Harbour Health Clinic',
    date: '27',
    month: 'OCT',
    year: '26',
    time: '08:00 AM – 02:00 PM',
    status: 'withdrawn',
  },
  {
    id: 5,
    title: 'General Practitioner – Morning Shift',
    hospitalName: "St. Mary's Hospital Sydney, NSW",
    date: '27',
    month: 'OCT',
    year: '26',
    time: '08:00 AM – 02:00 PM',
    status: 'pending',
  },
  {
    id: 6,
    title: 'Emergency Department – Night Shift',
    hospitalName: 'Royal Care Hospital',
    date: '27',
    month: 'OCT',
    year: '26',
    time: '08:00 PM – 06:00 AM',
    status: 'accepted',
  },
  {
    id: 7,
    title: 'Locum GP – Day Shift',
    hospitalName: 'Sunrise Medical Centre',
    date: '27',
    month: 'OCT',
    year: '26',
    time: '08:00 AM – 02:00 PM',
    status: 'rejected',
  },
  {
    id: 8,
    title: 'GP – Weekend Shift',
    hospitalName: 'Harbour Health Clinic',
    date: '27',
    month: 'OCT',
    year: '26',
    time: '08:00 AM – 02:00 PM',
    status: 'withdrawn',
  },
  {
    id: 9,
    title: 'General Practitioner – Morning Shift',
    hospitalName: "St. Mary's Hospital Sydney, NSW",
    date: '27',
    month: 'OCT',
    year: '26',
    time: '08:00 AM – 02:00 PM',
    status: 'pending',
  },
  {
    id: 10,
    title: 'Emergency Department – Night Shift',
    hospitalName: 'Royal Care Hospital',
    date: '27',
    month: 'OCT',
    year: '26',
    time: '08:00 PM – 06:00 AM',
    status: 'accepted',
  },
];
