import { MyShift } from '@/types/myShifts';

export const mockShifts: MyShift[] = [
  {
    id: 1,
    title: 'General Practitioner – Morning Shift',
    hospitalName: "St. Mary's Hospital Sydney, NSW",
    date: '27',
    month: 'OCT',
    year: '26',
    time: '08:00 AM – 02:00 PM',
    timesheetCreated: false,
    type: 'past',
  },
  {
    id: 2,
    title: 'Emergency Department – Night Shift',
    hospitalName: 'Royal Care Hospital',
    date: '25',
    month: 'OCT',
    year: '26',
    time: '08:00 PM – 06:00 AM',
    timesheetCreated: true,
    type: 'past',
  },
  {
    id: 3,
    title: 'Locum GP – Day Shift',
    hospitalName: 'Sunrise Medical Centre',
    date: '24',
    month: 'OCT',
    year: '26',
    time: '08:00 AM – 02:00 PM',
    timesheetCreated: true,
    type: 'past',
  },
  {
    id: 4,
    title: 'GP – Weekend Shift',
    hospitalName: 'Harbour Health Clinic',
    date: '23',
    month: 'OCT',
    year: '26',
    time: '08:00 AM – 02:00 PM',
    timesheetCreated: true,
    type: 'past',
  },
  {
    id: 5,
    title: 'Locum GP – Day Shift',
    hospitalName: 'Sunrise Medical Centre',
    date: '20',
    month: 'OCT',
    year: '26',
    time: '08:00 AM – 02:00 PM',
    timesheetCreated: false,
    type: 'past',
  },
  {
    id: 6,
    title: 'GP – Weekend Shift',
    hospitalName: 'Harbour Health Clinic',
    date: '21',
    month: 'OCT',
    year: '26',
    time: '08:00 AM – 02:00 PM',
    timesheetCreated: true,
    type: 'past',
  },
  {
    id: 7,
    title: 'Locum GP – Day Shift',
    hospitalName: 'Sunrise Medical Centre',
    date: '18',
    month: 'OCT',
    year: '26',
    time: '08:00 AM – 02:00 PM',
    timesheetCreated: false,
    type: 'past',
  },
  {
    id: 8,
    title: 'GP – Weekend Shift',
    hospitalName: 'Harbour Health Clinic',
    date: '19',
    month: 'OCT',
    year: '26',
    time: '08:00 AM – 02:00 PM',
    timesheetCreated: false,
    type: 'past',
  },
  {
    id: 9,
    title: 'General Practitioner – Morning Shift',
    hospitalName: "St. Mary's Hospital Sydney, NSW",
    date: '30',
    month: 'OCT',
    year: '26',
    time: '08:00 AM – 02:00 PM',
    timesheetCreated: false,
    type: 'upcoming',
  },
  {
    id: 10,
    title: 'Emergency Department – Night Shift',
    hospitalName: 'Royal Care Hospital',
    date: '01',
    month: 'NOV',
    year: '26',
    time: '08:00 PM – 06:00 AM',
    timesheetCreated: false,
    type: 'upcoming',
  },
  {
    id: 11,
    title: 'Locum GP – Day Shift',
    hospitalName: 'Sunrise Medical Centre',
    date: '03',
    month: 'NOV',
    year: '26',
    time: '08:00 AM – 02:00 PM',
    timesheetCreated: false,
    type: 'upcoming',
  },
  {
    id: 12,
    title: 'GP – Weekend Shift',
    hospitalName: 'Harbour Health Clinic',
    date: '07',
    month: 'NOV',
    year: '26',
    time: '08:00 AM – 02:00 PM',
    timesheetCreated: false,
    type: 'upcoming',
  },
];
