name: Cloudflare Deployment (Staging)

on:
  push:
    branches: [staging]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - name: Deploy to Cloudflare (Staging)
        run: npm run deploy:staging
